version: 0.2

env:
  parameter-store:
    ENV_FILE_FE: "REACT_APP_API"
    ENV_FILE_FE_2: "REACT_APP_API_2"
    ENV_FILE_FE_3: "REACT_APP_API_3"
    ENV_FILE_FE_4: "REACT_APP_API_4"
    ENV_FILE_BE: "BACK_END_API"


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $ENV_FILE_FE > ./front-end/.env
      - echo $ENV_FILE_FE_2 >> ./front-end/.env
      - echo $ENV_FILE_FE_3 >> ./front-end/.env
      - echo $ENV_FILE_FE_4 >> ./front-end/.env
      - echo $ENV_FILE_BE > ./.back-end.env
      - docker build -t $AWS_ECR_REPO:app_front_end -f ./front-end/docker/react/Dockerfile ./front-end
      - docker build -t $AWS_ECR_REPO:athena-nginx-front-end -f ./front-end/docker/nginx/Dockerfile ./front-end
      - docker build -t $AWS_ECR_REPO:app_back_end -f ./back-end/docker/django/Dockerfile ./back-end

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ECR_REPO:app_front_end
      - docker push $AWS_ECR_REPO:athena-nginx-front-end
      - docker push $AWS_ECR_REPO:app_back_end
  
artifacts:
  files:
    - '.back-end.env'
    - 'appspec.yml'
    - 'scripts/*'
    - 'docker-compose.deploy.yml'
  name: Athena-artifact
