version: "3.8"

services:
  nginx-front-end:
    image: "athena-nginx-front-end:latest"
    container_name: "athena-nginx-front-end"
    restart: always
    ports:
      - 80:80
    depends_on:
      - front-end
    networks:
      - athena

  front-end:
    image: "athena-front-end-app:latest"
    container_name: "athena-front-end-app"
    restart: always
    ports:
      - 3000:3000                           
    stdin_open: true
    networks:
      - athena
    env_file:
      - /home/centos/.env

networks:
  athena:
    driver: bridge